---

- hosts: node1
  become: yes
  gather_facts: yes
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: started
    - name: start the service
      service:
        name: httpd
        state: enabled
      notify: restarthttpd
  handlers:
    - name: restarthttpd
      service:
        name: httpd
        state: restarted
